[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fee_swap_router = "2ojyPqK6ZJbYtFZn6WFWVAFMoDQ4GpiZe6svpe1EBfB9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
fee_swap_router = "2ojyPqK6ZJbYtFZn6WFWVAFMoDQ4GpiZe6svpe1EBfB9"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
